// ==UserScript==
// @name Stash Checker
// @description Add checkmarks on porn websites to scenes/performers that are present in your own Stash instance.
// @version 1.1.0
// @author timo95
// @match *://adultanime.dbsearch.net/*
// @match *://www.brazzers.com/*
// @match *://coomer.su/*
// @match *://erommdtube.com/*
// @match *://fansdb.cc/*
// @match *://fansdb.xyz/*
// @match *://fansly.com/*
// @match *://www.slayed.com/*
// @match *://www.blacked.com/*
// @match *://www.tushy.com/*
// @match *://www.vixen.com/*
// @match *://www.blackedraw.com/*
// @match *://www.tushyraw.com/*
// @match *://www.deeper.com/*
// @match *://www.milfy.com/*
// @match *://www.wifey.com/*
// @match *://www.angelslove.xxx/*
// @match *://www.sensuallove.xxx/*
// @match *://www.wowgirlsblog.com/*
// @match *://www.ultrafilms.xxx/*
// @match *://www.18onlygirlsblog.com/*
// @match *://www.metart.com/*
// @match *://www.metartx.com/*
// @match *://www.sexart.com/*
// @match *://www.vivthomas.com/*
// @match *://www.thelifeerotic.com/*
// @match *://www.straplez.com/*
// @match *://www.errotica-archives.com/*
// @match *://www.domai.com/*
// @match *://www.goddessnudes.com/*
// @match *://www.eroticbeauty.com/*
// @match *://www.lovehairy.com/*
// @match *://www.alsscan.com/*
// @match *://www.rylskyart.com/*
// @match *://www.eternaldesire.com/*
// @match *://gayeroticvideoindex.com/*
// @match *://hobby.porn/*
// @match *://javdb.com/*
// @match *://javstash.org/*
// @match *://kemono.su/*
// @match *://onlyfans.com/*
// @match *://oreno3d.com/*
// @match *://pmvhaven.com/*
// @match *://pmvstash.org/*
// @match *://r18.dev/*
// @match *://shemalestardb.com/*
// @match *://stashdb.org/*
// @match *://theporndb.net/*
// @match *://warashi-asian-pornstars.fr/*
// @match *://www.adultfilmdatabase.com/*
// @match *://www.animecharactersdatabase.com/*
// @match *://www.babepedia.com/*
// @match *://www.clips4sale.com/*
// @match *://www.data18.com/*
// @match *://www.freeones.com/*
// @match *://www.iafd.com/*
// @match *://www.indexxx.com/*
// @match *://www.iwara.tv/*
// @match *://www.javlibrary.com/*
// @match *://www.manyvids.com/*
// @match *://www.minnano-av.com/*
// @match *://www.pornhub.com/*
// @match *://www.pornteengirl.com/*
// @match *://www.thenude.com/*
// @match *://xcity.jp/*
// @match *://xslist.org/*
// @connect localhost
// @connect *
// @downloadURL https://github.com/timo95/stash-checker/releases/latest/download/index.prod.user.js
// @grant GM.xmlHttpRequest
// @grant GM.getValue
// @grant GM.setValue
// @grant GM.deleteValue
// @grant GM.listValues
// @grant GM.registerMenuCommand
// @icon https://docs.stashapp.cc/assets/images/favicon.ico
// @license MIT
// @run-at document-end
// @source https://github.com/timo95/stash-checker
// @updateURL https://github.com/timo95/stash-checker/releases/latest/download/index.prod.meta.js
// ==/UserScript==
