import meta from "./package.json" with { type: "json" };

const metart = [
    "*://www.alsscan.com/*",
    "*://www.domai.com/*",
    "*://www.eroticbeauty.com/*",
    "*://www.errotica-archives.com/*",
    "*://www.eternaldesire.com/*",
    "*://www.goddessnudes.com/*",
    "*://www.lovehairy.com/*",
    "*://www.metart.com/*",
    "*://www.metartx.com/*",
    "*://www.rylskyart.com/*",
    "*://www.sexart.com/*",
    "*://www.straplez.com/*",
    "*://www.thelifeerotic.com/*",
    "*://www.vivthomas.com/*",
];

const vixen = [
    "*://www.blacked.com/*",
    "*://www.blackedraw.com/*",
    "*://www.deeper.com/*",
    "*://www.milfy.com/*",
    "*://www.slayed.com/*",
    "*://www.tushy.com/*",
    "*://www.tushyraw.com/*",
    "*://www.vixen.com/*",
    "*://www.wifey.com/*",
];

const wow = [
    "*://www.18onlygirlsblog.com/*",
    "*://www.angelslove.xxx/*",
    "*://www.sensuallove.xxx/*",
    "*://www.ultrafilms.xxx/*",
    "*://www.wowgirlsblog.com/*",
];

export default {
    name: "Stash Checker",
    description: meta.description,
    icon: "https://docs.stashapp.cc/assets/images/favicon.ico",
    version: meta.version,
    license: meta.license,
    author: meta.author.name,
    source: meta.repository.url,
    updateURL: meta.repository.url + "/releases/latest/download/index.prod.meta.js",
    downloadURL: meta.repository.url + "/releases/latest/download/index.prod.user.js",
    match: [
        "*://adultanime.dbsearch.net/*",
        "*://coomer.st/*",
        "*://erommdtube.com/*",
        "*://duga.jp/*",
        "*://fansdb.cc/*",
        "*://fansdb.xyz/*",
        "*://fansly.com/*",
        "*://fc2ppvdb.com/*",
        "*://gayeroticvideoindex.com/*",
        "*://hobby.porn/*",
        "*://javdb.com/*",
        "*://javstash.org/*",
        "*://kemono.cr/*",
        "*://onlyfans.com/*",
        "*://oreno3d.com/*",
        "*://pmvhaven.com/*",
        "*://pmvstash.org/*",
        "*://r18.dev/*",
        "*://shemalestardb.com/*",
        "*://stashdb.org/*",
        "*://theporndb.net/*",
        "*://warashi-asian-pornstars.fr/*",
        "*://www.adultfilmdatabase.com/*",
        "*://www.animecharactersdatabase.com/*",
        "*://www.avbase.net/*",
        "*://www.babepedia.com/*",
        "*://www.brazzers.com/*",
        "*://www.clips4sale.com/*",
        "*://www.data18.com/*",
		"*://www.freeones.com/*",
        "*://www.hegre.com/*",
        "*://www.iafd.com/*",
        "*://www.indexxx.com/*",
        "*://www.iwara.tv/*",
        "*://www.javlibrary.com/*",
        "*://www.manyvids.com/*",
        "*://www.minnano-av.com/*",
        "*://www.pornhub.com/*",
        "*://www.pornteengirl.com/*",
        "*://www.thenude.com/*",
        "*://xcity.jp/*",
        "*://xslist.org/*",
        ...metart,
        ...vixen,
        ...wow,
    ],
    require: [],
    grant: [
        "GM.xmlHttpRequest",
        "GM.getValue",
        "GM.setValue",
        "GM.deleteValue",
        "GM.listValues",
        "GM.registerMenuCommand",
    ],
    connect: [
        "localhost",
        "*"
    ],
    "run-at": "document-end",
};
