name: "Build userscript"
description: "Builds the userscript"
runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: "lts/*"
        cache: "npm"
        cache-dependency-path: userscript/package-lock.json
    - name: Install dependencies
      working-directory: userscript
      shell: bash
      run: npm ci

    - name: Build
      working-directory: userscript
      shell: bash
      run: npm run build
