import {deleteValue, getValue, setValue} from "./storage";
import {request} from "./request";
import {StashEndpoint} from "./dataTypes";

const BLOCKED_SITE_KEY = `blocked_${window.location.host}`.replace(/[.\-]/, "_");

let settingsModal: HTMLDivElement;
let settings: HTMLDivElement;

export let stashEndpoints: StashEndpoint[] = []

export async function initMenu() {
    GM.registerMenuCommand("Settings", openSettings, "s");

    if (await isSiteBlocked()) {
        GM.registerMenuCommand(`Activate for ${window.location.host}`, unblockSite, "a");
    } else {
        GM.registerMenuCommand(`Deactivate for ${window.location.host}`, blockSite, "d");
    }
}

export async function initSettings() {
    settingsModal = document.createElement("div");
    settingsModal.style.display = "none";
    settingsModal.classList.add("stashChecker", "modal");
    settingsModal.addEventListener("click", function (event) {
        if (event.target === settingsModal) {
            settingsModal.style.display = "none";
        }
    });

    let defaultData: StashEndpoint[] = [{
        name: "Localhost",
        url: "http://localhost:9999/graphql",
        key: "",
    }];
    stashEndpoints = await getValue<StashEndpoint[]>("stashEndpoints", defaultData);

    settings = document.createElement("div");
    settings.id = "stashChecker-settings"
    settings.classList.add("stashChecker", "settings");
    settings.innerHTML = "<h2>Stash Endpoints</h2>"
    let description = document.createElement("p");
    description.classList.add("stashChecker", "sub-heading");
    description.innerHTML = "The GraphQL endpoint URL can be generated by appending '/graphql' to your Stash base URL. The API key can be found on your security settings page. Leave the field empty, if none is required.";
    settings.append(description);
    settings.append(await initEndpoints());
    settingsModal.append(settings);
    document.body.append(settingsModal);
    await updateEndpoints();
}

async function initEndpoints(): Promise<HTMLDivElement> {
    let endpoints = document.createElement("div");
    endpoints.id = "stashChecker-endpoints"
    endpoints.classList.add("stashChecker", "endpoints");
    return endpoints;
}

async function updateEndpoints() {
    let endpoints = document.getElementById("stashChecker-endpoints")
    let endpointList = stashEndpoints.map((endpoint: StashEndpoint, index: number) => {
        let div = document.createElement("div");
        div.classList.add("stashChecker", "endpoint");
        div.innerHTML = `<div><h3>${endpoint.name}</h3><p>${endpoint.url}</p></div>`
        getVersion(endpoint, div.querySelector("h3"))
        let editButton = document.createElement("button");
        editButton.classList.add("stashChecker", "btn", "btn-primary")
        editButton.setAttribute("data-index", index.toString());
        editButton.addEventListener("click", editEndpointListener);
        editButton.innerHTML = "Edit";
        div.append(editButton);
        let deleteButton = document.createElement("button");
        deleteButton.classList.add("stashChecker", "btn", "btn-danger")
        deleteButton.setAttribute("data-index", index.toString());
        deleteButton.addEventListener("click", deleteEndpointListener);
        deleteButton.innerHTML = "Delete";
        div.append(deleteButton);
        return div;
    });
    // Add Endpoint
    let div = document.createElement("div");
    div.classList.add("stashChecker", "endpoint");
    div.innerHTML = "<div></div>"
    let addButton = document.createElement("button");
    addButton.classList.add("stashChecker", "btn", "btn-primary")
    addButton.addEventListener("click", addEndpointListener);
    addButton.innerHTML = "Add";
    div.append(addButton);
    endpointList.push(div)
    endpoints.replaceChildren(...endpointList)
}

async function addEndpointListener(this: HTMLButtonElement) {
    let newEndpoint: StashEndpoint = {
        name: prompt("Name:")?.trim()?? "",
        url: prompt("URL:")?.trim()?? "",
        key: prompt("API Key:")?.trim()?? "",
    };
    stashEndpoints.push(newEndpoint);
    void setValue("stashEndpoints", stashEndpoints);
    await updateEndpoints();
}

async function editEndpointListener(this: HTMLButtonElement) {
    let index = parseInt(this.getAttribute("data-index"));
    let oldEndpoint: StashEndpoint = stashEndpoints[index];

    stashEndpoints[index] = {
        name: prompt("Name:", oldEndpoint.name)?.trim() ?? oldEndpoint.name,
        url: prompt("URL:", oldEndpoint.url)?.trim() ?? oldEndpoint.url,
        key: prompt("API Key:", oldEndpoint.key)?.trim() ?? oldEndpoint.key,
    };
    void setValue("stashEndpoints", stashEndpoints);
    await updateEndpoints();
}

async function deleteEndpointListener(this: HTMLButtonElement) {
    let index = parseInt(this.getAttribute("data-index"));
    stashEndpoints.splice(index, 1);
    void setValue("stashEndpoints", stashEndpoints);
    await updateEndpoints();
}

export async function isSiteBlocked(): Promise<boolean> {
    return await getValue(BLOCKED_SITE_KEY, false);
}

async function blockSite() {
    await setValue(BLOCKED_SITE_KEY, true);
    window.location.reload();
}

async function unblockSite() {
    await deleteValue(BLOCKED_SITE_KEY);
    window.location.reload();
}

async function openSettings() {
    settingsModal.style.display = "initial";
}

async function getVersion(endpoint: StashEndpoint, element: HTMLElement) {
    let onload = (data: any) => {
        element.innerHTML += `<span class="version"> (${data.version})</span>`
    }
    let onerror = (message?: string) => {
        let explanation = "no connection";
        if (message) explanation = message.length < 30 ? message?.trim() : "wrong path"
        element.innerHTML += `<span class="version"> (${explanation})</span>`
    }
    await request(endpoint, {query: "version{version}", onload, onerror})
}
